version: "3"
services:
  web: 
     build: ./
     volumes:
     - "./php.conf:/etc/nginx/conf.d/default.conf"
     - "./nginx.conf:/etc/nginx/nginx.conf"
     - "./app:/opt/app"
     - "./supervisor.conf:/etc/supervisor.conf"
     privileged: true
     cap_add:
       - ALL
     ports:
     - "80:80"
     - "8080:8080"
     - "9001:9001"